Made init script for CentOS based on https://gist.github.com/yummylogs/6459539

diff --git a/logstash-forwarder.init b/logstash-forwarder.init
--- a/logstash-forwarder.init
+++ b/logstash-forwarder.init
@@ -1,95 +1,105 @@
-#! /bin/sh
-### BEGIN INIT INFO
-# Provides:          skeleton
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Example initscript
-# Description:       This file should be used to construct scripts to be
-#                    placed in /etc/init.d.
-### END INIT INFO
-
-# Author: Jordan Sissel <jordan.sissel@dreamhost.com>
-
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="log shipper"
+#!/bin/sh
+#
+#   /etc/init.d/logstash-forwarder
+#
+#   Starts and stops Lumberjack as a "daemon".
+#   Based on https://gist.github.com/yummylogs/6459539
+#
+# chkconfig: 2345 30 70
+# description: Starts and stops Lumberjack as a daemon.
+ 
+# The name of this service
 NAME=logstash-forwarder
-DAEMON=/opt/logstash-forwarder/bin/logstash-forwarder
-DAEMON_ARGS="-config /etc/logstash-forwarder -spool-size 100 -log-to-syslog"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
-
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
-. /lib/init/vars.sh
-. /lib/lsb/init-functions
-
-COMMAND="cd /var/run; exec $DAEMON $DAEMON_ARGS"
-
-do_start() {
-  # Skip if it's already running
-  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec /bin/sh --test > /dev/null || return 1
-
-  cd /var/run
-  # Actually start it now.
-  start-stop-daemon --start --quiet --make-pidfile --background \
-    --pidfile $PIDFILE --exec /bin/sh -- -c "$COMMAND" || return 2
+ 
+### Start Configuration Options ###
+ 
+# The JSON config to use
+LJ_CONFIG=/etc/logstash-forwarder.conf
+ 
+# The Lumberjack binary wrapper
+LJ_BIN=/opt/logstash-forwarder/bin/logstash-forwarder
+ 
+# Any Lumberjack options
+LJ_OPTS="-spool-size 1000"
+ 
+# The log file for local info
+LJ_LOG=/var/log/logstash-forwarder/logstash-forwarder
+mkdir -p $(dirname $LJ_LOG)
+ 
+# The PID file
+PID_FILE=/var/run/logstash-forwarder
+ 
+# The command to daemonize
+DAEMON="nohup ${LJ_BIN} -config ${LJ_CONFIG} ${LJ_OPTS} >>${LJ_LOG} 2>&1 &"
+ 
+### End Configuration Options ###
+ 
+. /etc/init.d/functions
+ 
+check_prereqs() {
+  if [ -z ${LJ_BIN} ]; then
+    echo "ERROR: Unable to locate Lumberjack binary, make sure it's installed."
+    exit 1
+  elif [ ! -f ${LJ_CONFIG} ]; then
+    echo "ERROR: LJ_CONFIG (${LJ_CONFIG}) doesn't exist."
+    exit 1
+  elif [ ! -d `dirname ${LJ_LOG}` ]; then
+    echo "ERROR: LJ_LOG parent directory (`dirname ${LJ_LOG}`) doesn't exist."
+    exit 1
+  fi
 }
-
-do_stop()
-{
-  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
-  RETVAL="$?"
-  [ "$RETVAL" = 2 ] && return 2
-  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-  [ "$?" = 2 ] && return 2
-  rm -f $PIDFILE
-  return "$RETVAL"
+ 
+start() {
+  check_prereqs
+ 
+  echo -n $"Starting $NAME: "
+ 
+  daemon --check $NAME --pidfile $PID_FILE $DAEMON
+ 
+  RETVAL=$?
+ 
+  if [ $RETVAL -ne 0 ]; then
+    echo_failure
+    echo
+  else
+    PID=$(pgrep -f $NAME)
+    echo -n $PID > $PID_FILE
+    echo_success
+    echo
+  fi
+  return $RETVAL
 }
-
+ 
+stop () {
+  echo -n $"Stopping $NAME: "
+  killproc -p $PID_FILE $NAME
+  RETVAL=$?
+  echo
+  return $RETVAL
+}
+ 
+restart () {
+  stop
+  start
+}
+ 
 case "$1" in
   start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-    do_start
-    case "$?" in
-      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
+    start
     ;;
   stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
+    stop
     ;;
   status)
-    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    status -p $PID_FILE $NAME
     ;;
-  restart|force-reload)
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-          0) log_end_msg 0 ;;
-          1) log_end_msg 1 ;; # Old process is still running
-          *) log_end_msg 1 ;; # Failed to start
-        esac
-      ;;
-      *)
-        # Failed to stop
-        log_end_msg 1
-      ;;
-    esac
+  restart)
+    restart
     ;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-    exit 3
+    echo "Usage: $0 {start|stop|status}"
+    exit 2
     ;;
 esac
-
-:
+ 
+exit $?
